services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: gerador_certificado
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7
    ports:
      - 6379:6379
